### PR TITLE
Please add this to main branch and send me invitation of Org

### PR DESCRIPTION
**Pull request by Mubshr07**
Hello, I want to contribute to open-source projects. I want to build a good portfolio on Git Hub, I need PR, issues, contributions, and all other stuff. Please consider my request and send me the invitation.

Please  invite me in your organization.

### CODE REVIEW

**Review by NS007-dev — CHANGES_REQUESTED** [review]
Hi @Mubshr07, thank you so much for your contribution, before I can merge this pr, please can you remove lines 60-61, as I have an automated bot that does that for you instead. Once this is complete, I will send you an invite to our organisation! Thanks!

**Comment by Mubshr07** [comment]
I changed the code as you instructed, push to my repo and update it. Now I don't know how to raise the pull-request. Can you help me to guide about "How to raise pull request again after implementing the changes of a review?"

**Review by Mubshr07 — COMMENTED** [review]
README file content changed as you guide me. Thank you.  ;)

**Comment by NS007-dev** [comment]
> I changed the code as you instructed, push to my repo and update it. Now I don't know how to raise the pull-request. Can you help me to guide about "How to raise pull request again after implementing the changes of a review?"

As you have already opened this pull request, whatever changes you commit and push, will be pushed to the same pull request, meaning you won't need to raise another pull request. 
To make seperate pull requests, you can create a seperate branch in your forked version of the repo. If you want to read more into this, see this link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
This link has an in depth description of branches and pull requests.

**Review by NS007-dev — APPROVED** [review]
Thank you so much for the changes!

**Comment by NS007-dev** [comment]
Any more support or any questions you have, feel free to ask me here.

**Comment by NS007-dev** [comment]
###### [Our Website 🌐](https://app-choreography.github.io/) | [Repositories 📚](https://github.com/orgs/App-Choreography/repositories) | [LinkFree Profile 🔗](http://linkfree.eddiehub.org/App-Choreography)

You have received an email to join, or press this link - https://github.com/App-Choreography - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
image

### When you join our org, you will be automatically be part of our community team, where you will get updates, and news about our org!

### We are so happy you have joined! Welcome to App Choreography! 🥳

**Comment by NS007-dev** [comment]
@all-contributors please add @Mubshr07 for content

**Pull request merged**
