### PR TITLE
Added emojis for better visibility

### PR DESCRIPTION
**Pull request by Rudra2198**

### CODE REVIEW

**Comment by Rudra2198** [comment]
@CodingSpecies  Could you please merge this

**Review by hacker20028 — APPROVED** [review]
Looks good to me👍

**Review by CodingSpecies — APPROVED** [review]
Thank you so much for your helpful additions @Rudra2198 .
I apologise for the late review.

**Comment by CodingSpecies** [comment]
@all-contributors please add @Rudra2198 for content

**Pull request merged**
